import React from 'react';
import { ReportResult } from '../types';

interface PrintReportTemplateProps {
  report: ReportResult;
  companyName?: string;
  filtersSummary?: string;
}

export const PrintReportTemplate: React.FC<PrintReportTemplateProps> = ({
  report,
  companyName = 'Shield Max / Al-Bunyan Trading Co.',
  filtersSummary = 'All Records',
}) => {
  return (
    <div className="hidden print:block p-8 bg-white text-black font-sans min-h-screen">
      {/* Print Header */}
      <div className="flex items-center justify-between border-b pb-4 mb-6">
        <div>
          <h1 className="text-2xl font-bold text-slate-900">{companyName}</h1>
          <h2 className="text-xl font-semibold text-slate-700 mt-1">{report.metadata.nameEn}</h2>
          <p className="text-sm text-slate-500 mt-0.5">{report.metadata.nameAr}</p>
        </div>
        <div className="text-right text-xs text-slate-500">
          <p>Generated: {new Date(report.metadata.generatedAt).toLocaleString()}</p>
          <p>Scope: {filtersSummary}</p>
        </div>
      </div>

      {/* KPI Highlights (if present) */}
      {report.kpis && report.kpis.length > 0 && (
        <div className="grid grid-cols-4 gap-4 mb-6 border p-4 rounded-md bg-slate-50">
          {report.kpis.slice(0, 4).map((kpi, idx) => (
            <div key={idx}>
              <p className="text-xs text-slate-500 font-medium">{kpi.label}</p>
              <p className="text-base font-bold text-slate-900 mt-0.5">{kpi.value}</p>
            </div>
          ))}
        </div>
      )}

      {/* Report Data Table */}
      <table className="w-full text-xs border-collapse border border-slate-300">
        <thead>
          <tr className="bg-slate-100 border-b border-slate-300">
            {report.columns.map((col) => (
              <th
                key={col.id}
                className="border border-slate-300 px-3 py-2 text-left font-semibold text-slate-800"
              >
                <div>{col.label}</div>
                {col.labelAr && <div className="text-[10px] text-slate-500 font-normal">{col.labelAr}</div>}
              </th>
            ))}
          </tr>
        </thead>
        <tbody>
          {report.rows.map((row, rowIdx) => (
            <tr key={rowIdx} className={rowIdx % 2 === 0 ? 'bg-white' : 'bg-slate-50'}>
              {report.columns.map((col) => {
                const val = row[col.id];
                const isCurrency = col.type === 'currency' && typeof val === 'number';
                return (
                  <td key={col.id} className="border border-slate-300 px-3 py-1.5 text-slate-700">
                    {isCurrency ? `${val.toFixed(3)} KWD` : val ?? '-'}
                  </td>
                );
              })}
            </tr>
          ))}
        </tbody>
        {/* Totals Footer */}
        {report.totals && Object.keys(report.totals).length > 0 && (
          <tfoot>
            <tr className="bg-slate-200 font-bold border-t-2 border-slate-400">
              {report.columns.map((col, idx) => {
                if (idx === 0) {
                  return (
                    <td key={col.id} className="border border-slate-300 px-3 py-2 text-slate-900">
                      TOTAL / الإجمالي
                    </td>
                  );
                }
                const totalVal = report.totals[col.id];
                const isNum = typeof totalVal === 'number';
                return (
                  <td key={col.id} className="border border-slate-300 px-3 py-2 text-slate-900">
                    {isNum ? `${totalVal.toFixed(3)} KWD` : ''}
                  </td>
                );
              })}
            </tr>
          </tfoot>
        )}
      </table>

      {/* Print Footer */}
      <div className="mt-8 pt-4 border-t text-center text-xs text-slate-400">
        Page 1 • System Generated by Shield Max ERP
      </div>
    </div>
  );
};
